# src/db/migrations/versions/8455bde36b98_add_models.py
"""Add models

Revision ID: 8455bde36b98
Revises: 
Create Date: 2025-08-13 18:45:24.170438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8455bde36b98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activities',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.CheckConstraint('level <= 3', name='max_level'),
        sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'buildings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('building_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'organization_activities',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('activity_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    op.create_table(
        'phone_numbers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=True),
        sa.Column('phone_number', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # === ТЕСТОВЫЕ ДАННЫЕ (по 10 записей в каждую таблицу) ===
    op.execute("""
        INSERT INTO activities (id, name, parent_id, level) VALUES
            (1, 'Еда', NULL, 1),
            (2, 'Автомобили', NULL, 1),
            (3, 'Мясная продукция', 1, 2),
            (4, 'Молочная продукция', 1, 2),
            (5, 'Грузовые', 2, 2),
            (6, 'Легковые', 2, 2),
            (7, 'Запчасти', 6, 3),
            (8, 'Аксессуары', 6, 3),
            (9, 'Фрукты', 1, 2),
            (10, 'Овощи', 1, 2);
    """)
    
    op.execute("""
        INSERT INTO buildings (id, address, latitude, longitude) VALUES
            (1, 'г. Москва, ул. Ленина, 1', 55.7558, 37.6176),
            (2, 'г. Москва, ул. Блюхера, 32/1', 55.7600, 37.6200),
            (3, 'г. Москва, ул. Пушкина, 10', 55.7610, 37.6250),
            (4, 'г. Москва, ул. Чехова, 5', 55.7620, 37.6300),
            (5, 'г. Москва, ул. Толстого, 20', 55.7630, 37.6350),
            (6, 'г. Москва, ул. Гоголя, 15', 55.7640, 37.6400),
            (7, 'г. Москва, пр-т Мира, 100', 55.7650, 37.6450),
            (8, 'г. Москва, ул. Ломоносова, 7', 55.7660, 37.6500),
            (9, 'г. Москва, ул. Тургенева, 3', 55.7670, 37.6550),
            (10, 'г. Москва, ул. Некрасова, 12', 55.7680, 37.6600);
    """)

    op.execute("""
        INSERT INTO organizations (id, name, building_id) VALUES
            (1, 'ООО Рога и Копыта', 1),
            (2, 'АО Молочные радости', 2),
            (3, 'ИП Иванов', 3),
            (4, 'ИП Петров', 4),
            (5, 'ООО МашСервис', 5),
            (6, 'АО Автодеталь', 6),
            (7, 'ООО ФруктыПро', 7),
            (8, 'ООО ОвощиПро', 8),
            (9, 'ИП Сидоров', 9),
            (10, 'ООО ГрузТех', 10);
    """)

    op.execute("""
        INSERT INTO phone_numbers (id, organization_id, phone_number) VALUES
            (1, 1, '2-222-222'),
            (2, 1, '3-333-333'),
            (3, 2, '8-923-666-13-13'),
            (4, 3, '900-111-1111'),
            (5, 4, '900-222-2222'),
            (6, 5, '900-333-3333'),
            (7, 6, '900-444-4444'),
            (8, 7, '900-555-5555'),
            (9, 8, '900-666-6666'),
            (10, 9, '900-777-7777');
    """)

    op.execute("""
        INSERT INTO organization_activities (organization_id, activity_id) VALUES
            (1, 3),
            (1, 7),
            (2, 4),
            (3, 5),
            (4, 6),
            (5, 7),
            (6, 8),
            (7, 9),
            (8, 10),
            (9, 2);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_numbers')
    op.drop_table('organization_activities')
    op.drop_table('organizations')
    op.drop_table('buildings')
    op.drop_table('activities')
    # ### end Alembic commands ###
